# Generated by Django 5.1.7 on 2025-03-19 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('house_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('barangay', models.CharField(max_length=100)),
                ('purok', models.CharField(max_length=100)),
                ('respondent', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(max_length=50)),
                ('household_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='records.household')),
            ],
        ),
    ]
