# Generated by Django 5.1.7 on 2025-03-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='household_id',
            new_name='household',
        ),
    ]
