# Generated by Django 5.1.7 on 2025-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_household_id_person_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
