# Generated by Django 5.1.7 on 2025-04-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_person_age_person_age_class_person_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='home_record',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='home_screening',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='immunization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_of_service_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nutrition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
