# Generated by Django 5.1.7 on 2025-04-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_person_birth_length_person_birth_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='home_record',
            new_name='infant_home_record',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name_of_service_provider',
            new_name='infant_service_provider',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='home_screening',
            new_name='newborn_home_record',
        ),
        migrations.RemoveField(
            model_name='person',
            name='immunization',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='person',
            name='infant_immunization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='newborn_home_screening',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='newborn_immunization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='newborn_service_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
