# Generated by Django 5.1.7 on 2025-04-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_rename_home_record_person_infant_home_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='five9_first_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_first_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_first_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_immunization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_other_vaccine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='under5_immunization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='under5_nutrition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
