# Generated by Django 5.1.7 on 2025-04-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_person_five9_first_brand_person_five9_first_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='five9_booster_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_booster_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_booster_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_second_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_second_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='five9_second_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
