# Generated by Django 5.1.7 on 2025-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_persondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
