# Generated by Django 5.1.7 on 2025-04-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_family_person_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
