# Generated by Django 5.1.7 on 2025-04-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_person_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
