# Generated by Django 5.1.7 on 2025-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_persondata_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='newborn_home_record',
            new_name='newborn_booklet',
        ),
        migrations.RemoveField(
            model_name='person',
            name='newborn_home_screening',
        ),
        migrations.AlterField(
            model_name='person',
            name='newborn_immunization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
