# Generated by Django 5.1.7 on 2025-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_rename_newborn_home_record_person_newborn_booklet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='newborn_bcg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
