# Generated by Django 5.1.7 on 2025-04-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_person_newborn_bcg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='infant_home_record',
        ),
        migrations.RemoveField(
            model_name='person',
            name='infant_service_provider',
        ),
    ]
