# Generated by Django 5.1.7 on 2025-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_remove_person_infant_home_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='infant_immunization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='newborn_immunization',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
