# Generated by Django 5.1.7 on 2025-04-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_person_infant_immunization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='under5_nutrition',
        ),
        migrations.AddField(
            model_name='person',
            name='under5_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='under5_muac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='under5_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
