# Generated by Django 5.1.7 on 2025-04-30 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_person_under5_height_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='five9_immunization',
            new_name='five19_immunization',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_booster_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_booster_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_booster_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_first_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_first_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_first_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_other_vaccine',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_second_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_second_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='five9_second_place',
        ),
    ]
