# Generated by Django 5.1.7 on 2025-04-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_rename_five9_immunization_person_five19_immunization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='adolescent_booster_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_booster_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_booster_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_first_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_first_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_first_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_immunization',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_other_vaccine',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_second_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_second_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adolescent_second_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_booster_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_booster_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_booster_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_first_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_first_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_first_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_other_vaccine',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_second_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_second_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='senior_second_place',
        ),
        migrations.AlterField(
            model_name='person',
            name='senior_flu_vaccine',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='senior_pneumonia_vaccine',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
