# Generated by Django 5.1.7 on 2025-04-30 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_remove_person_adolescent_booster_brand_and_more'),
        ('records', '0023_set_default_json_fields'),
    ]

    operations = [
    ]
