# Generated by Django 5.1.7 on 2025-04-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_merge_20250430_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='adult_booster_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_booster_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_booster_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_first_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_first_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_first_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_flu_vaccine',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_other_vaccine',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_second_brand',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_second_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adult_second_place',
        ),
    ]
