# Generated by Django 5.1.7 on 2025-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_alter_person_newborn_immunization'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='buntis_toggle',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
