# Generated by Django 5.1.7 on 2025-05-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_person_buntis_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='postpartum_toggle',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
