# Generated by Django 5.1.7 on 2025-05-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_person_postpartum_toggle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='newborn_bcg',
            new_name='expanded_newborn_screening',
        ),
        migrations.RemoveField(
            model_name='person',
            name='newborn_booklet',
        ),
    ]
