# Generated by Django 5.1.7 on 2025-05-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_rename_newborn_bcg_person_expanded_newborn_screening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_length',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_weight',
        ),
        migrations.RemoveField(
            model_name='person',
            name='newborn_service_provider',
        ),
        migrations.AddField(
            model_name='person',
            name='newborn_hearing_screening',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='newborn_immunization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
