# Generated by Django 5.1.7 on 2025-05-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_remove_person_birth_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sexually_active',
        ),
        migrations.AddField(
            model_name='person',
            name='fp_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
