# Generated by Django 5.1.7 on 2025-05-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_remove_person_sexually_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_drinking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_drug_user',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_smoking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
