# Generated by Django 5.1.7 on 2025-05-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0032_person_is_drinking_person_is_drug_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_pwd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pwd_toggle',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
