# Generated by Django 5.1.7 on 2025-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0033_person_is_pwd_person_pwd_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='prenatal_checkup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tetanus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='under5_immunization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
