# Generated by Django 5.1.7 on 2025-05-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0034_alter_person_birth_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='iron_with_folic',
            new_name='pregnancy_order',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name_of_midwife',
            new_name='prenatal_location',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='place_of_giving_birth',
            new_name='prenatal_provider',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_mens',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postpartum_checkup',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postpartum_gave_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postpartum_toggle',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pregnant_gave_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tetanus',
        ),
        migrations.RemoveField(
            model_name='person',
            name='want_fp',
        ),
        migrations.AlterField(
            model_name='person',
            name='prenatal_checkup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
