# Generated by Django 5.1.7 on 2025-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0035_rename_iron_with_folic_person_pregnancy_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='senior_flu_vaccine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='senior_pneumonia_vaccine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
