# Generated by Django 5.1.7 on 2025-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0036_alter_person_senior_flu_vaccine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='disability_type',
        ),
        migrations.AddField(
            model_name='person',
            name='sub_health_condition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
