# Generated by Django 5.1.7 on 2025-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0037_remove_person_disability_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='high_risk_activities',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
