# Generated by Django 5.1.7 on 2025-05-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0038_person_high_risk_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='geriatric_screening',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='philpen_risk_assessment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='visual_acquity_test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
