# Generated by Django 5.1.7 on 2025-05-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0039_person_geriatric_screening_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='philpen_risk_assessment',
            new_name='senior_philpen_risk_assessment',
        ),
        migrations.AddField(
            model_name='person',
            name='twenty59_philpen_risk_assessment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
