# Generated by Django 5.1.7 on 2025-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0040_rename_philpen_risk_assessment_person_senior_philpen_risk_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='breast_cancer_screening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='fourteen49_cervical_cancer_screening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='thirty69_cervical_cancer_screening',
            field=models.TextField(blank=True, null=True),
        ),
    ]
