# Generated by Django 5.1.7 on 2025-05-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0041_person_breast_cancer_screening_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fourteen49_cervical_cancer_screening',
            new_name='cervical_cancer_screening',
        ),
        migrations.RemoveField(
            model_name='person',
            name='thirty69_cervical_cancer_screening',
        ),
        migrations.AlterField(
            model_name='person',
            name='buntis_toggle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pwd_toggle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
