"""
Django settings for household_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

from environ import Env
env = Env()
env.read_env()
ENVIRONMENT = env('ENVIRONMENT', default='development')  # Default to development for safety

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

if ENVIRONMENT == 'development':
    DEBUG = True
    # Use safe defaults for local development only
    LOGIN_EMAIL = env('LOGIN_EMAIL', default='dev@example.com')
    LOGIN_PASSWORD = env('LOGIN_PASSWORD', default='devpassword')
    SECRET_KEY = env('SECRET_KEY', default='django-insecure-CHANGE_THIS_KEY_FOR_DEV')
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "localhost:8000"]
else:
    DEBUG = False
    # In production, require secrets to be set in environment variables
    LOGIN_EMAIL = env('LOGIN_EMAIL')
    LOGIN_PASSWORD = env('LOGIN_PASSWORD')
    SECRET_KEY = env('SECRET_KEY')
    # Set your production domains here
    ALLOWED_HOSTS = [
        "your-production-domain.com",
        "household-profiling.up.railway.app",
        "interchange.proxy.rlwy.net"
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'dashboard',
    'records',
    'reports',
    'tailwind',
    'theme',
    'django_browser_reload',
    'admin_honeypot'
]

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost:8000"
]
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'household_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'household_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='railway'),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD', default='cfYYSFDAJOauVDunnSVwKlVFYebUMbAb'),
        'HOST': env('DB_HOST', default='interchange.proxy.rlwy.net'),
        'PORT': env('DB_PORT', default='46582'),
    }
}

POSTGRES_LOCALLY = ENVIRONMENT == 'development'
if ENVIRONMENT == 'production' or POSTGRES_LOCALLY == True:
    DATABASES['default'] = dj_database_url.parse(
        env(
            'DATABASE_URL',
            default='postgres://postgres:cfYYSFDAJOauVDunnSVwKlVFYebUMbAb@interchange.proxy.rlwy.net:46582/railway'
        )
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'theme/static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_USERNAME_BLACKLIST = ['admin', 'root', 'superuser', 'secretsite']

# WARNING: Never commit real secrets or production credentials to version control!